### PR TITLE
update developing-apbs-locally.adoc with style edits

### PR DESCRIPTION
**Pull request by pwright**
some language fixes and standard adoc mark up

### CODE REVIEW

**Comment by pwright** [comment]
@wtrocki you've already reviewed these changes?

**Review by wtrocki — COMMENTED** [review]
Reviewed.

**Comment by wtrocki** [comment]
@finp Good to go, but please also change base as it's  basing on your fork - it should be upstream.

**Comment by pwright** [comment]
@wtrocki  closed for https://github.com/aerogear/mobile-core/pull/21

**Pull request closed without merging**
